using System;
/*
Name: Jacob Hutson
Date: 7/11/2026
Class: CSE 210
Description: This class handles all of the Console writing for the program. Additionally, all of the content 
for the customer information was generated by AI, and has been marked with 1. despite not being actual code 
advice.
Sources:
1. Gemini Code Advice
2. In Class Notes
*/

class Program
{
    static void Main(string[] args)
    {
        Address jph_domesticAddress = new Address("1600 Amphitheatre Pkwy", "Mountain View", "CA", "USA"); // 1.
        Customer jph_domesticCustomer = new Customer("Jane Doe", jph_domesticAddress); // 1.
        Order jph_domesticOrder = new Order(jph_domesticCustomer);

        jph_domesticOrder.AddProduct(new Product("Wireless Ergonomic Mouse", "MS-202", 45.99, 1)); // 1.
        jph_domesticOrder.AddProduct(new Product("4K USB-C Monitor", "MN-705", 299.00, 2)); // 1.
        jph_domesticOrder.AddProduct(new Product("AA Rechargeable Batteries", "BT-112", 14.50, 3)); // 1.

        Address jph_internationalAddress = new Address("10-12 Military Rd", "Neutral Bay", "NSW", "Australia"); // 1.
        Customer jph_internationalCustomer = new Customer("John Smith", jph_internationalAddress); // 1.
        Order jph_internationalOrder = new Order(jph_internationalCustomer);

        jph_internationalOrder.AddProduct(new Product("Mechanical Keyboard", "KB-900", 120.00, 1)); // 1.
        jph_internationalOrder.AddProduct(new Product("Braided Nylon USB-C Cable", "CB-404", 8.25, 4)); // 1.

        Console.WriteLine("=================================================");
        Console.WriteLine("                     ORDER 1                     ");
        Console.WriteLine("=================================================");
        Console.WriteLine(jph_domesticOrder.GenerateShippingLabel());
        Console.WriteLine(jph_domesticOrder.GeneratePackingLabel());
        Console.WriteLine($"Final Order Bill: ${jph_domesticOrder.CalculateSubtotal():F2}");
        Console.WriteLine("\n\n");

        Console.WriteLine("=================================================");
        Console.WriteLine("                     ORDER 2                     ");
        Console.WriteLine("=================================================");
        Console.WriteLine(jph_internationalOrder.GenerateShippingLabel());
        Console.WriteLine(jph_internationalOrder.GeneratePackingLabel());
        Console.WriteLine($"Final Order Bill: ${jph_internationalOrder.CalculateSubtotal():F2}");
        Console.WriteLine("=================================================");
    }
}