using System;
/*
Name: Jacob Hutson
Date: 7/18/2026
Class: CSE 210
Description: This class handles all of the Console writing for the program. Additionally, all of the content 
for the activity information was generated by AI, and has been marked with 1. despite not being actual code 
advice.
Sources:
1. Gemini Code Advice
2. In Class Notes
*/

public class Program
{
    static void Main(string[] args)
    {
        List<Activity> jph_activities = new List<Activity>();

        Running jph_run = new Running("12 Jul 2026", 30, 3.0); // 1.
        Cycling jph_cycling = new Cycling("12 Jul 2026", 45, 15.0); // 1.
        Swimming jph_swim = new Swimming("12 Jul 2026", 20, 20); // 1.

        jph_activities.Add(jph_run);
        jph_activities.Add(jph_cycling);
        jph_activities.Add(jph_swim);

        Console.WriteLine("===============================================================================");
        Console.WriteLine("                           FITNESS ACTIVITY LOG                                ");
        Console.WriteLine("===============================================================================\n");

        foreach (Activity jph_activity in jph_activities)
        {
            Console.WriteLine(jph_activity.GetSummary());
        }

        Console.WriteLine("\n===============================================================================");
    }
}