using System;
/*
Name: Jacob Hutson
Date: 7/11/2026
Class: CSE 210
Description: This class handles all of the Console writing for the program. Additionally, all of the content 
for the video and comment information was generated by AI, and has been marked with 1. despite not being 
actual code advice.
Sources:
1. Gemini Code Advice
2. In Class Notes
*/

public class Program
{
    static void Main(string[] args)
    {
        List<Video> jph_videos = new List<Video>();

        Video jph_video1 = new Video("Top 10 Smart Home Gadgets 2026", "TechZone", 620); // 1.
        jph_video1.AddComment(new Comment("Alice", "That smart lock looks incredibly sleek. Might buy it!")); // 1.
        jph_video1.AddComment(new Comment("Bob", "Does the hub require a subscription fee?")); // 1.
        jph_video1.AddComment(new Comment("Charlie", "Great overview, thanks for the timestamp breakdowns.")); // 1.
        jph_videos.Add(jph_video1);

        Video jph_video2 = new Video("Ultrabook Review: Ultimate Portability", "GadgetByte", 845); // 1.
        jph_video2.AddComment(new Comment("David", "The battery life test you did was super helpful.")); // 1.
        jph_video2.AddComment(new Comment("Emily", "Can this handle lightweight video editing on the go?")); // 1.
        jph_video2.AddComment(new Comment("Frank", "A bit too expensive for my blood, but great review.")); // 1.
        jph_videos.Add(jph_video2);

        Video jph_video3 = new Video("How to Build a Custom Mechanical Keyboard", "KeyCraft", 1205); // 1.
        jph_video3.AddComment(new Comment("Grace", "The sound test at the end was pure ASMR. Bliss.")); // 1.
        jph_video3.AddComment(new Comment("Henry", "Which switches did you use? They sound wonderfully tactile.")); // 1.
        jph_video3.AddComment(new Comment("Ivy", "Solderless PCBs make this so much less intimidating for beginners.")); // 1.
        jph_videos.Add(jph_video3);

        Console.WriteLine("==================================================");
        Console.WriteLine("              YOUTUBE TRACKING REPORT             ");
        Console.WriteLine("==================================================\n");

        foreach (Video jph_video in jph_videos)
        {
            Console.WriteLine($"Title:  {jph_video._jphTitle}");
            Console.WriteLine($"Author: {jph_video._jphAuthor}");
            Console.WriteLine($"Length: {jph_video._jphLength} seconds");
            Console.WriteLine($"Total Comments: {jph_video.GetCommentCount()}");
            Console.WriteLine("--------------------------------------------------");
            Console.WriteLine("Comments:");

            foreach (Comment jph_comment in jph_video.GetComments())
            {
                Console.WriteLine($"  - @{jph_comment._jphName}: \"{jph_comment._jphText}\"");
            }

            Console.WriteLine("\n==================================================\n");
        }
    }
}