using System;
/*
Name: Jacob Hutson
Date: 7/18/2026
Class: CSE 210
Description: This class handles all of the Console writing for the program. Additionally, all of the content 
for the event information was generated by AI, and has been marked with 1. despite not being actual code 
advice.
Sources:
1. Gemini Code Advice
2. In Class Notes
*/

public class Program
{
    static void Main(string[] args)
    {
        List<Event> jph_eventsList = new List<Event>();

        Address jph_lectureAddress = new Address("101 Innovation Way", "Tech City", "CA", "USA"); // 1.
        Lecture jph_lecture = new Lecture(
            "AI Architecture In 2026", // 1.
            "A technical breakdown of next-generation multi-agent execution engines.", // 1.
            "August 18, 2026", // 1.
            "2:00 PM", // 1.
            jph_lectureAddress, 
            "Dr. Marcus Vance", // 1.
            250 // 1.
        );
        jph_eventsList.Add(jph_lecture);

        Address jph_receptionAddress = new Address("500 Luxury Lane", "New York", "NY", "USA"); // 1.
        Reception jph_reception = new Reception(
            "Corporate Mixer & Gala", // 1.
            "An evening dinner reception for project stakeholders and investors.", // 1.
            "September 09, 2026", // 1.
            "6:00 PM", // 1.
            jph_receptionAddress, 
            "register@corporatemixer.com" // 1.
        );
        jph_eventsList.Add(jph_reception);

        Address jph_outdoorAddress = new Address("Bayview Waterfront Park Pavillion B", "San Francisco", "CA", "USA"); // 1.
        OutdoorGathering jph_outdoorGathering = new OutdoorGathering(
            "Annual Community Arts Festival", // 1.
            "An open-air venue gathering featuring regional acoustic musical acts and physical art displays.", // 1.
            "July 25, 2026", // 1.
            "11:00 AM", // 1.
            jph_outdoorAddress, 
            "Clear, sunny conditions with local marine layers. Expected temperature high around 72°F." // 1.
        );
        jph_eventsList.Add(jph_outdoorGathering);

        Console.WriteLine("==================================================================");
        Console.WriteLine("                   EVENT MARKETING DASHBOARD                      ");
        Console.WriteLine("==================================================================\n");

        int jph_INDEX = 1;
        foreach (Event jph_event in jph_eventsList)
        {
            Console.WriteLine($"--- MARKETING GENERATION: ITEM #{jph_INDEX} ---");
            
            Console.WriteLine("\n[1. SHORT DESCRIPTION MESSAGE]");
            Console.WriteLine(jph_event.GetShortDescription());

            Console.WriteLine("\n[2. STANDARD DETAILS MESSAGE]");
            Console.WriteLine(jph_event.GetStandardDetails());

            Console.WriteLine("\n[3. FULL DETAILS MESSAGE]");
            Console.WriteLine(jph_event.GetFullDetails());

            Console.WriteLine("\n==================================================================\n");
            jph_INDEX++;
        }
    }
}